server:
  servlet:
    context-path: "/api"
spring:
  flyway:
    driver-class-name: org.postgresql.Driver
    user: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/linda
    baseline-on-migrate: true
  devtools:
    restart:
      log-condition-evaluation-delta: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/linda
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        show_sql: true
        ddl-auto: validate
    generate-ddl: true
minio:
  bucket: images
  url: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin

rsa.private-key: classpath:certs/private.pem
rsa.public-key: classpath:certs/public.pem


