server:
  servlet:
    context-path: "/api"
spring:
  flyway:
    driver-class-name: org.postgresql.Driver
    user: postgres
    password: lxqtpr2021
    url: jdbc:postgresql://localhost:5432/postgres
    baseline-on-migrate: true
  devtools:
    restart:
      log-condition-evaluation-delta: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: lxqtpr2021
  jpa:
    properties:
      hibernate:
        show_sql: true
        ddl-auto: validate
    generate-ddl: false
minio:
  bucket: images
  url: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin