server:
  servlet:
    context-path: "/api"
spring:
  devtools:
    restart:
      log-condition-evaluation-delta: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: lxqtpr2021
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update
        ddl-auto: update
minio:
  bucket: images
  url: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
